'use client';

import { useEffect, useRef } from 'react';
import type { Theme } from '../ExperienceProvider';

/**
 * Pointer-lit leather surface (raw WebGL, no 3D library).
 *
 * A tileable procedural height map (public/textures/leather-height.webp,
 * generated by scripts/build-brand-assets.mjs) is turned into normals in the
 * fragment shader and lit by a soft spotlight that follows the pointer — or
 * drifts slowly on touch devices. A light 2D canvas adds a few dust motes that
 * only glow inside the beam.
 *
 * Performance & fallbacks:
 *  - renders only while on screen and while the tab is visible
 *  - device-pixel ratio capped (1.5 desktop, 1.25 small screens)
 *  - reduced motion → a single static frame, no particles
 *  - no WebGL / texture failure → the CSS `.leather` surface underneath shows
 *
 * The light position is also written to CSS custom properties (--light-x,
 * --light-y, 0–1) on `hostRef` so DOM layers (logo sheen, shadows) can react.
 */

const VERT = `attribute vec2 p;void main(){gl_Position=vec4(p,0.,1.);}`;

const FRAG = `
precision highp float;
uniform sampler2D uH;
uniform vec2 uRes;
uniform vec2 uLight;
uniform float uTile;
uniform vec3 uBase;
uniform vec3 uWarm;
uniform vec3 uSpec;
uniform float uAmb;
uniform float uRadius;
uniform float uReveal;
uniform float uNormal;
uniform float uCrease;

// Two rotated scales of the same tileable map break up visible repetition.
const mat2 ROT = mat2(0.8, -0.6, 0.6, 0.8);
float h(vec2 uv){ return texture2D(uH, uv).r * 0.72 + texture2D(uH, ROT * uv * 1.73 + 0.37).r * 0.28; }

void main(){
  vec2 fc = gl_FragCoord.xy;
  vec2 uv = vec2(fc.x, uRes.y - fc.y) / uTile;
  float e = 1.0 / 512.0;
  float hc = h(uv);
  float hx = h(uv + vec2(e, 0.0)) - h(uv - vec2(e, 0.0));
  float hy = h(uv + vec2(0.0, e)) - h(uv - vec2(0.0, e));
  vec3 n = normalize(vec3(-hx * uNormal, hy * uNormal, 1.0));

  vec3 lp = vec3(uLight, max(uRes.x, uRes.y) * 0.22);
  vec3 L = normalize(lp - vec3(fc, 0.0));
  float d = length(uLight - fc) / max(uRes.x, uRes.y);
  float fall = exp(-(d * d) / (uRadius * uRadius));

  float diff = max(dot(n, L), 0.0);
  vec3 H = normalize(L + vec3(0.0, 0.0, 1.0));
  float spec = pow(max(dot(n, H), 0.0), 42.0);
  float crease = smoothstep(0.02, 0.5, hc);

  vec3 col = uBase * (uAmb + (1.0 - uAmb) * diff * (0.35 + 0.65 * fall));
  col = mix(col * uCrease, col, crease);
  col += uWarm * fall * diff * 0.55;
  col += uSpec * spec * (0.25 + 0.75 * fall) * crease;

  vec2 q = fc / uRes - 0.5;
  col *= 1.0 - dot(q, q) * 0.75;
  col *= uReveal;

  float dn = fract(sin(dot(fc, vec2(12.9898, 78.233))) * 43758.5453);
  col += (dn - 0.5) / 255.0;
  gl_FragColor = vec4(col, 1.0);
}`;

type Palette = {
  base: number[];
  warm: number[];
  spec: number[];
  amb: number;
  radius: number;
  normal: number;
  crease: number;
  mote: string;
};

const PALETTES: Record<Theme, Palette> = {
  dark: {
    base: [0.235, 0.163, 0.128],
    warm: [0.28, 0.19, 0.12],
    spec: [0.5, 0.46, 0.42],
    amb: 0.3,
    radius: 0.42,
    normal: 2.0,
    crease: 0.78,
    mote: '255, 238, 214',
  },
  light: {
    base: [0.93, 0.885, 0.825],
    warm: [0.07, 0.05, 0.02],
    spec: [0.18, 0.16, 0.13],
    amb: 0.82,
    radius: 0.55,
    normal: 1.25,
    crease: 0.92,
    mote: '150, 112, 70',
  },
};

interface Props {
  theme: Theme;
  reducedMotion: boolean;
  hostRef: React.RefObject<HTMLElement | null>;
  className?: string;
  particlesClassName?: string;
}

export function LeatherCanvas({ theme, reducedMotion, hostRef, className, particlesClassName }: Props) {
  const glRef = useRef<HTMLCanvasElement>(null);
  const dustRef = useRef<HTMLCanvasElement>(null);
  const themeRef = useRef(theme);
  const redrawRef = useRef<() => void>(() => {});

  useEffect(() => {
    themeRef.current = theme;
    redrawRef.current();
  }, [theme]);

  useEffect(() => {
    const canvas = glRef.current;
    const dustCanvas = dustRef.current;
    const host = hostRef.current;
    if (!canvas || !host) return;

    const gl = canvas.getContext('webgl', { antialias: false, alpha: false, powerPreference: 'low-power' });
    if (!gl) return; // CSS fallback stays visible

    const compile = (type: number, src: string) => {
      const s = gl.createShader(type)!;
      gl.shaderSource(s, src);
      gl.compileShader(s);
      if (!gl.getShaderParameter(s, gl.COMPILE_STATUS)) {
        console.warn('[LeatherCanvas] shader error', gl.getShaderInfoLog(s));
        return null;
      }
      return s;
    };
    const vs = compile(gl.VERTEX_SHADER, VERT);
    const fs = compile(gl.FRAGMENT_SHADER, FRAG);
    if (!vs || !fs) return;
    const prog = gl.createProgram()!;
    gl.attachShader(prog, vs);
    gl.attachShader(prog, fs);
    gl.linkProgram(prog);
    if (!gl.getProgramParameter(prog, gl.LINK_STATUS)) return;
    gl.useProgram(prog);

    const buf = gl.createBuffer();
    gl.bindBuffer(gl.ARRAY_BUFFER, buf);
    gl.bufferData(gl.ARRAY_BUFFER, new Float32Array([-1, -1, 3, -1, -1, 3]), gl.STATIC_DRAW);
    const loc = gl.getAttribLocation(prog, 'p');
    gl.enableVertexAttribArray(loc);
    gl.vertexAttribPointer(loc, 2, gl.FLOAT, false, 0, 0);

    const u = (n: string) => gl.getUniformLocation(prog, n);
    const U = {
      res: u('uRes'),
      light: u('uLight'),
      tile: u('uTile'),
      base: u('uBase'),
      warm: u('uWarm'),
      spec: u('uSpec'),
      amb: u('uAmb'),
      radius: u('uRadius'),
      reveal: u('uReveal'),
      normal: u('uNormal'),
      crease: u('uCrease'),
    };

    let textureReady = false;
    let disposed = false;
    const tex = gl.createTexture();
    const img = new Image();
    img.decoding = 'async';
    img.src = '/textures/leather-height.webp';
    img.onload = () => {
      if (disposed) return;
      gl.bindTexture(gl.TEXTURE_2D, tex);
      gl.texImage2D(gl.TEXTURE_2D, 0, gl.LUMINANCE, gl.LUMINANCE, gl.UNSIGNED_BYTE, img);
      gl.generateMipmap(gl.TEXTURE_2D);
      gl.texParameteri(gl.TEXTURE_2D, gl.TEXTURE_WRAP_S, gl.REPEAT);
      gl.texParameteri(gl.TEXTURE_2D, gl.TEXTURE_WRAP_T, gl.REPEAT);
      gl.texParameteri(gl.TEXTURE_2D, gl.TEXTURE_MIN_FILTER, gl.LINEAR_MIPMAP_LINEAR);
      gl.texParameteri(gl.TEXTURE_2D, gl.TEXTURE_MAG_FILTER, gl.LINEAR);
      textureReady = true;
      start = performance.now();
      requestFrame();
    };

    const small = () => window.innerWidth < 700;
    let dpr = 1;
    let W = 0;
    let H = 0;
    const resize = () => {
      dpr = Math.min(window.devicePixelRatio || 1, small() ? 1.25 : 1.5);
      const rect = canvas.getBoundingClientRect();
      W = Math.max(1, Math.round(rect.width * dpr));
      H = Math.max(1, Math.round(rect.height * dpr));
      canvas.width = W;
      canvas.height = H;
      gl.viewport(0, 0, W, H);
      if (dustCanvas) {
        dustCanvas.width = Math.round(rect.width * Math.min(window.devicePixelRatio || 1, 2));
        dustCanvas.height = Math.round(rect.height * Math.min(window.devicePixelRatio || 1, 2));
      }
      seedMotes();
      requestFrame();
    };

    // Light position in 0–1 host coordinates (y down).
    const target = { x: 0.32, y: 0.3 };
    const light = { x: reducedMotion ? 0.38 : 0.1, y: reducedMotion ? 0.32 : 0.15 };
    let pointerActive = false;
    let lastPointer = 0;

    const onPointer = (e: PointerEvent) => {
      if (e.pointerType !== 'mouse') return;
      const r = host.getBoundingClientRect();
      target.x = (e.clientX - r.left) / r.width;
      target.y = (e.clientY - r.top) / r.height;
      pointerActive = true;
      lastPointer = performance.now();
      requestFrame();
    };
    const onLeave = () => {
      pointerActive = false;
    };

    // Dust motes
    type Mote = { x: number; y: number; r: number; vx: number; vy: number; phase: number; a: number };
    let motes: Mote[] = [];
    function seedMotes() {
      if (!dustCanvas || reducedMotion) return;
      const count = small() ? 16 : 34;
      motes = Array.from({ length: count }, () => ({
        x: Math.random(),
        y: Math.random(),
        r: 0.5 + Math.random() * 1.4,
        vx: (Math.random() - 0.5) * 0.004,
        vy: -0.004 - Math.random() * 0.008,
        phase: Math.random() * Math.PI * 2,
        a: 0.35 + Math.random() * 0.65,
      }));
    }
    const dctx = dustCanvas?.getContext('2d') ?? null;

    let start = performance.now();
    let raf = 0;
    let visible = true;
    let lastCss = { x: -1, y: -1 };

    const draw = (now: number) => {
      raf = 0;
      if (!textureReady) return;
      const p = PALETTES[themeRef.current];
      const t = (now - start) / 1000;

      if (!reducedMotion) {
        if (!pointerActive || now - lastPointer > 4000) {
          // idle drift: a slow figure-of-eight across the upper half
          target.x = 0.5 + Math.sin(t * 0.13) * 0.32;
          target.y = 0.36 + Math.sin(t * 0.21) * 0.16;
        }
        const k = pointerActive ? 0.075 : 0.02;
        light.x += (target.x - light.x) * k;
        light.y += (target.y - light.y) * k;
      }
      const reveal = reducedMotion ? 1 : Math.min(1, t / 1.6);
      const eased = 1 - Math.pow(1 - reveal, 3);

      gl.uniform2f(U.res, W, H);
      gl.uniform2f(U.light, light.x * W, (1 - light.y) * H);
      // Grain scales with the viewport so phones see fine grain, not pebbles.
      gl.uniform1f(U.tile, Math.min(480, Math.max(250, (W / dpr) * 0.3)) * dpr);
      gl.uniform3fv(U.base, p.base);
      gl.uniform3fv(U.warm, p.warm);
      gl.uniform3fv(U.spec, p.spec);
      gl.uniform1f(U.amb, p.amb);
      gl.uniform1f(U.radius, p.radius);
      gl.uniform1f(U.normal, p.normal);
      gl.uniform1f(U.crease, p.crease);
      gl.uniform1f(U.reveal, 0.15 + 0.85 * eased);
      gl.drawArrays(gl.TRIANGLES, 0, 3);
      if (canvas.dataset.ready !== 'true') canvas.dataset.ready = 'true';

      if (Math.abs(light.x - lastCss.x) > 0.002 || Math.abs(light.y - lastCss.y) > 0.002) {
        host.style.setProperty('--light-x', light.x.toFixed(3));
        host.style.setProperty('--light-y', light.y.toFixed(3));
        lastCss = { x: light.x, y: light.y };
      }

      if (dctx && dustCanvas && motes.length) {
        const dw = dustCanvas.width;
        const dh = dustCanvas.height;
        const scale = dw / Math.max(1, dustCanvas.clientWidth);
        dctx.clearRect(0, 0, dw, dh);
        for (const m of motes) {
          m.x += m.vx * 0.016 + Math.sin(t * 0.6 + m.phase) * 0.00012;
          m.y += m.vy * 0.016;
          if (m.y < -0.02) {
            m.y = 1.02;
            m.x = Math.random();
          }
          if (m.x < -0.02) m.x = 1.02;
          if (m.x > 1.02) m.x = -0.02;
          const dx = (m.x - light.x) * (dw / dh);
          const dy = m.y - light.y;
          const glow = Math.exp(-(dx * dx + dy * dy) / 0.06);
          const alpha = m.a * glow * (0.55 + 0.45 * Math.sin(t * 1.3 + m.phase)) * eased;
          if (alpha < 0.02) continue;
          dctx.beginPath();
          dctx.fillStyle = `rgba(${p.mote}, ${alpha.toFixed(3)})`;
          dctx.arc(m.x * dw, m.y * dh, m.r * scale, 0, Math.PI * 2);
          dctx.fill();
        }
      }

      if (!reducedMotion && visible && !document.hidden && !covered()) requestFrame();
    };

    // Paused while a dialog or the menu covers the page (scroll lock class).
    const covered = () => document.documentElement.classList.contains('is-locked');

    function requestFrame() {
      if (!raf) raf = requestAnimationFrame(draw);
    }
    redrawRef.current = requestFrame;

    const io = new IntersectionObserver(([entry]) => {
      visible = entry.isIntersecting;
      if (visible) requestFrame();
    });
    io.observe(host);

    const onVisibility = () => {
      if (!document.hidden) requestFrame();
    };
    const lockObserver = new MutationObserver(() => {
      if (!covered()) requestFrame();
    });
    lockObserver.observe(document.documentElement, { attributes: true, attributeFilter: ['class'] });

    const ro = new ResizeObserver(resize);
    ro.observe(canvas);
    resize();

    host.addEventListener('pointermove', onPointer, { passive: true });
    host.addEventListener('pointerleave', onLeave);
    document.addEventListener('visibilitychange', onVisibility);

    return () => {
      disposed = true;
      img.onload = null;
      cancelAnimationFrame(raf);
      io.disconnect();
      ro.disconnect();
      lockObserver.disconnect();
      host.removeEventListener('pointermove', onPointer);
      host.removeEventListener('pointerleave', onLeave);
      document.removeEventListener('visibilitychange', onVisibility);
      redrawRef.current = () => {};
      gl.deleteTexture(tex);
      gl.deleteBuffer(buf);
      gl.deleteProgram(prog);
    };
  }, [hostRef, reducedMotion]);

  return (
    <>
      <canvas ref={glRef} className={className} aria-hidden="true" />
      {!reducedMotion && <canvas ref={dustRef} className={particlesClassName} aria-hidden="true" />}
    </>
  );
}
